//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contain
    {
        public int documentId { get; set; }
        public int termId { get; set; }
        public int position { get; set; }
    
        public virtual Document Document { get; set; }
        public virtual Term Term { get; set; }
    }
}
